Cadc 10929
opencadc/opencadc.github.io pull request #7
Opened 2022-09-08 23:24 UTC by zombiepig01

Added storage inventory documentation

2022-09-14 19:44 UTC, pdowler reviewed
example haproxy config is `bind :8443` ... well, as I later found out, there are 2 sets of config here and I got confused :-(

why is there quick-start/{luskan|minoc|baldur} and quick-start/example_storage_site/{luskan|minoc}?? some have port 443 and some 8443

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/README.md
> +  - `ringhold` - metadata validation after a site policy change.  Subtle difference with above.
ringhold removes a namespace; that's not a validation operation, just a quicker way to do removal of a subset

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/database/si.dll
> +GRANT ALL ON TABLESPACE si_data TO tapuser;
Take a look at this for the minimum 

https://github.com/opencadc/docker-base/blob/master/cadc-postgresql-dev/src/init/init-content.sh

I still think we'd be  better off just pointing people to `cadc-postgresql-dev`.

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/example_storage_site/haproxy/haproxy.cfg
> +
why acl(s)?   #cognitive-load

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/baldur/config/catalina.properties
> +tomcat.connector.proxyPort=443
proxy port disagrees with haproxy

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/luskan/config/catalina.properties
> +tomcat.connector.proxyPort=443
proxy port disagrees with haproxy

2022-09-14 19:44 UTC, pdowler commented on storage-inventory/quick-start/minoc/config/catalina.properties
> +tomcat.connector.proxyPort=443
proxy port disagrees with haproxy

2022-09-14 20:20 UTC, pdowler requested changes

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/example_storage_site/luskan/config/luskan.properties
> +org.opencadc.luskan.resourceID=ivo://cadc.nrc.ca/minoc/luskan
resourceID is wrong

note that ivo://cadc.nrc.ca/{luskan|minoc|raven} are used by very destructive local integration tests and shouldn't be used except by developers.... I'll probably change that to not use `cadc.nrc.ca` but for now something else is advisable.

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/example_storage_site/luskan/docker-compose.yml
> +    image: bucket.canfar.net/luskan:20210408T233844
this will obviously not work and solution is a separate story.... what about just `luskan:latest` which is what you get if you follow the build instructions and is recognizable as a local image?

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/fenwick/config/fenwick.properties
> +org.opencadc.fenwick.artifactSelector=all
`all` here but you also include an artifact-filter.sql file

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/luskan/config/luskan.properties
> +org.opencadc.luskan.resourceID=ivo://cadc.nrc.ca/uvic/luskan
this is an existing prod resourceID

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/minoc/README.md
> +    - [s3](https://github.com/opencadc/storage-inventory/tree/master/cadc-storage-adapter-s3)
Please remove `s3` from this list; it doesn't work.

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/minoc/config/minoc.properties
> +org.opencadc.minoc.resourceID=ivo://cadc.nrc.ca/cadc/minoc
a different existing prod resourceID?

2022-09-14 20:20 UTC, pdowler commented on storage-inventory/quick-start/tantar/README.md
> +    - [s3](https://github.com/opencadc/storage-inventory/tree/master/cadc-storage-adapter-s3)
remove s3

2023-02-06 13:41 UTC, at88mph requested changes

2023-02-06 13:41 UTC, at88mph commented on storage-inventory/ops/global_site/ratik/README.md
> +This [`docker-compose.yml`](docker-compose.yml) file will need to be editted for your local environment.
* edited

2023-03-20 20:00 UTC, closed without merging